name: Feature request
description: Propose a modular vRP3 feature
title: "[FEATURE] "
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed modular solution
    validations:
      required: true
  - type: textarea
    id: compatibility
    attributes:
      label: Core and compatibility impact
