-- components list https://wiki.rage.mp/index.php?title=Weapons_Components
local cfg = {}

cfg.weapons = {	-- gtype, name, useable, components{name, hash, value}, skins{name, hash, value}
	["WEAPON_ADVANCEDRIFLE"] = 		{"Assult", "Advanced Rifle", true, {}, {}},
	["WEAPON_ASSAULTRIFLE_MK2"] = 	{"Assult", "Assault Rifle Mk II", true, {}, {}},
	["WEAPON_BULLPUPRIFLE_MK2"] = 	{"Assult", "Bullpup Rifle Mk II", true, {}, {}},
	["WEAPON_BULLPUPRIFLE"] = 		{"Assult", "Bullpup Rifle", true, {}, {}},
	["WEAPON_CARBINERIFLE_MK2"] = 	{"Assult", "Carbine Rifle Mk II", true, {}, {}},
	["WEAPON_CARBINERIFLE"] = 		{"Assult", "Carbine Rifle", true, {}, {}},
	["WEAPON_COMPACTRIFLE"] = 		{"Assult", "Compact Rifle", true, {}, {}},
	["WEAPON_SPECIALCARBINE_MK2"] = {"Assult", "Special Carbine Mk II", true, {}, {}},
	["WEAPON_SPECIALCARBINE"] = 	{"Assult", "Special Carbine", true, {}, {}},
	["WEAPON_ASSAULTRIFLE"] = 		{"Assult", "Assault Rifle", true, {}, {}},
	["WEAPON_MILITARYRIFLE"] = 		{"Assult", "Military Rifle", true, {}, {}},
	["WEAPON_HEAVYRIFLE"] = 		{"Assult", "Heavy Rifle", true, {}, {}},
	
	["WEAPON_COMPACTLAUNCHER"] = 	{"Heavy", "Compact Grenade Launcher", true, {}, {}},
	["WEAPON_FIREWORK"] = 			{"Heavy", "Firework Launcher", true, {}, {}},
	["WEAPON_GRENADELAUNCHER"] = 	{"Heavy", "Grenade Launcher", true, {}, {}},
	["WEAPON_GRENADELAUNCHER_SM"] = {"Heavy", "Grenade Launcher Smoke", true, {}, {}},
	["WEAPON_HOMINGLAUNCHER"] = 	{"Heavy", "Homing Launcher", true, {}, {}},
	["WEAPON_MINIGUN"] = 			{"Heavy", "Minigun", true, {}, {}},
	["WEAPON_RAILGUN"] = 			{"Heavy", "Railgun", true, {}, {}},
	["WEAPON_RPG"] = 				{"Heavy", "RPG", true, {}, {}},
	["WEAPON_RAYMINIGUN"] = 		{"Heavy", "Widowmaker", true, {}, {}},
	["WEAPON_EMPLAUNCHER"] = 		{"Heavy", "Compact EMP Launcher", true, {}, {}},

	["WEAPON_COMBATMG_MK2"] = 		{"LMG", "Combat MG Mk II", true, {}, {}},
	["WEAPON_COMBATMG"] = 			{"LMG", "Combat MG", true, {}, {}},
	["WEAPON_GUSENBERG"] = 			{"LMG", "Gusenberg Sweeper", true, {}, {}},
	["WEAPON_MG"] = 				{"LMG", "MG", true, {}, {}},

	["WEAPON_DAGGER"] = 			{"Melee", "Antique Cavalry Dagger", true, {}, {}},
	["WEAPON_BAT"] = 				{"Melee", "Baseball Bat", true, {}, {}},
	["WEAPON_BATTLEAXE"] = 			{"Melee", "Battle Axe", true, {}, {}},
	["WEAPON_BOTTLE"] = 			{"Melee", "Broken Bottle", true, {}, {}},
	["WEAPON_CROWBAR"] = 			{"Melee", "Crowbar", true, {}, {}},
	["WEAPON_FLASHLIGHT"] = 		{"Melee", "Flashlight", true, {}, {}},
	["WEAPON_GOLFCLUB"] = 			{"Melee", "Golf Club", true, {}, {}},
	["WEAPON_HAMMER"] = 			{"Melee", "Hammer", true, {}, {}},
	["WEAPON_HATCHET"] = 			{"Melee", "Hatchet", true, {}, {}},
	["WEAPON_KNIFE"] = 				{"Melee", "Knife", true, {}, {}},
	["WEAPON_KNUCKLE"] = 			{"Melee", "Brass Knuckles", true, {}, {}},
	["WEAPON_MACHETE"] = 			{"Melee", "Machete", true, {}, {}},
	["WEAPON_NIGHTSTICK"] = 		{"Melee", "Nightstick", true, {}, {}},
	["WEAPON_WRENCH"] = 			{"Melee", "Pipe Wrench", true, {}, {}},
	["WEAPON_POOLCUE"] = 			{"Melee", "Pool Cue", true, {}, {}},
	["WEAPON_STONE_HATCHET"] = 		{"Melee", "Stone Hatchet", true, {}, {}},
	["WEAPON_SWITCHBLADE"] = 		{"Melee", "Switchblade", true, {}, {}},

	["WEAPON_FIREEXTINGUISHER"] = 	{"Miscellaneous", "Fire Extinguisher", true, {}, {}},
	["WEAPON_PETROLCAN"] = 			{"Miscellaneous", "Jerry Can", true, {}, {}},
	["WEAPON_HAZARDCAN"] = 			{"Miscellaneous", "Hazardous Jerry Can", true, {}, {}},
	["WEAPON_FERTILIZERCAN"] = 		{"Miscellaneous", "Fertilizer Can", true, {}, {}},
	["GADGET_PARACHUTE"] = 			{"Miscellaneous", "Parachute", true, {}, {}},

	["WEAPON_APPISTOL"] = 			{"Pistol", "AP Pistol", true, {}, {}},
	["WEAPON_CERAMICPISTOL"] = 		{"Pistol", "Ceramic Pistol", true, {}, {}},
	["WEAPON_COMBATPISTOL"] = 		{"Pistol", "Combat Pistol", true, {}, {}},
	["WEAPON_DOUBLEACTION"] = 		{"Pistol", "Double Action Revolver", true, {}, {}},
	["WEAPON_FLAREGUN"] = 			{"Pistol", "Flare Gun", true, {}, {}},
	["WEAPON_GADGETPISTOL"] = 		{"Pistol", "Perico Pistol", true, {}, {}},
	["WEAPON_HEAVYPISTOL"] = 		{"Pistol", "Heavy Pistol", true, {}, {}},
	["WEAPON_MARKSMANPISTOL"] = 	{"Pistol", "Marksman Pistol", true, {}, {}},
	["WEAPON_NAVYREVOLVER"] = 		{"Pistol", "Navy Revolver", true, {}, {}},
	["WEAPON_PISTOL"] = 			{"Pistol", "Pistol", true, {}, {}},
	["WEAPON_PISTOL50"] = 			{"Pistol", "Pistol .50", true, {}, {}},
	["WEAPON_PISTOL_MK2"] = 		{"Pistol", "Pistol Mk II", true, {}, {}},
	["WEAPON_RAYPISTOL"] = 			{"Pistol", "Up-n-Atomizer", true, {}, {}},
	["WEAPON_REVOLVER"] = 			{"Pistol", "Heavy Revolver", true, {}, {}},
	["WEAPON_REVOLVER_MK2"] = 		{"Pistol", "Heavy Revolver Mk II", true, {}, {}},
	["WEAPON_SNSPISTOL"] = 			{"Pistol", "SNS Pistol", true, {}, {}},
	["WEAPON_SNSPISTOL_MK2"] = 		{"Pistol", "SNS Pistol Mk II", true, {}, {}},
	["WEAPON_STUNGUN"] = 			{"Pistol", "Stun Gun", true, {}, {}},
	["WEAPON_VINTAGEPISTOL"] = 		{"Pistol", "Vintage Pistol", true, {}, {}},

	["WEAPON_ASSAULTSHOTGUN"] = 	{"Shotguns", "Assault Shotguns", true, {}, {}},
	["WEAPON_BULLPUPSHOTGUN"] = 	{"Shotguns", "Bullpup Shotguns", true, {}, {}},
	["WEAPON_DBSHOTGUN"] = 			{"Shotguns", "Double Barrel Shotguns", true, {}, {}},
	["WEAPON_HEAVYSHOTGUN"] = 		{"Shotguns", "Heavy Shotguns", true, {}, {}},
	["WEAPON_MUSKET"] = 			{"Shotguns", "Musket", true, {}, {}},
	["WEAPON_PUMPSHOTGUN_MK2"] = 	{"Shotguns", "Pump Shotguns Mk II", true, {}, {}},
	["WEAPON_PUMPSHOTGUN"] = 		{"Shotguns", "Pump Shotguns", true, {}, {}},
	["WEAPON_SAWNOFFSHOTGUN"] = 	{"Shotguns", "Sawed-Off Shotguns", true, {}, {}},
	["WEAPON_AUTOSHOTGUN"] = 		{"Shotguns", "Sweeper Shotguns", true, {}, {}},
	["WEAPON_COMBATSHOTGUN"] = 		{"Shotguns", "Combat Shotguns", true, {}, {}},

	["WEAPON_HEAVYSNIPER_MK2"] = 	{"Snipers", "Heavy Snipers Mk II", true, {}, {}},
	["WEAPON_HEAVYSNIPER"] = 		{"Snipers", "Heavy Snipers", true, {}, {}},
	["WEAPON_MARKSMANRIFLE_MK2"] = 	{"Snipers", "Marksman Rifle Mk II", true, {}, {}},
	["WEAPON_MARKSMANRIFLE"] = 		{"Snipers", "Marksman Rifle", true, {}, {}},
	["WEAPON_SNIPERRIFLE"] = 		{"Snipers", "Snipers Rifle", true, {}, {}},

	["WEAPON_ASSAULTSMG"] = 		{"SMG", "Assault SMG", true, {}, {}},
	["WEAPON_COMBATPDW"] = 			{"SMG", "Combat PDW", true, {}, {}},
	["WEAPON_MACHINEPISTOL"] = 		{"SMG", "Machine Pistol", true, {}, {}},
	["WEAPON_MICROSMG"] = 			{"SMG", "Micro SMG", true, {}, {}},
	["WEAPON_MINISMG"] = 			{"SMG", "Mini SMG", true, {}, {}},
	["WEAPON_SMG_MK2"] = 			{"SMG", "SMG Mk II", true, {}, {}},
	["WEAPON_SMG"] = 				{"SMG", "SMG", true, {}, {}},
	["WEAPON_RAYCARBINE"] = 		{"SMG", "Unholy Hellbringer", true, {}, {}},

	["WEAPON_BALL"] = 				{"Throwables", "Baseball", true, {}, {}},
	["WEAPON_BZGAS"] = 				{"Throwables", "BZ Gas", true, {}, {}},
	["WEAPON_FLARE"] = 				{"Throwables", "Flare", true, {}, {}},
	["WEAPON_GRENADE"] = 			{"Throwables", "Grenade", true, {}, {}},
	["WEAPON_MOLOTOV"] = 			{"Throwables", "Molotov Cocktail", true, {}, {}},
	["WEAPON_PIPEBOMB"] = 			{"Throwables", "Pipe Bombs", true, {}, {}},
	["WEAPON_PROXMINE"] = 			{"Throwables", "Proximity Mines", true, {}, {}},
	["WEAPON_SNOWBALL"] = 			{"Throwables", "Snowballs", true, {}, {}},
	["WEAPON_STICKYBOMB"] = 		{"Throwables", "Sticky Bomb", true, {}, {}},
	["WEAPON_SMOKEGRENADE"] = 		{"Throwables", "Tear Gas", true, {}, {}},

}

cfg.components = {
	--[display name] = component name
	clip = {
		["Default Clip"] = "CLIP_01", 
		["Extended Clip"] = "CLIP_02",
		["Drum Magazine"] = "CLIP_03",
	},
	optic = {
		["Iron Sights"] = "SIGHT_01",
		["Holographic"] = "COMPONENT_AT_SIGHTS",
		["Holographic_smg"] = "COMPONENT_AT_SIGHTS_SMG",
		["Mounted Scope"] = "COMPONENT_AT_PI_RAIL_02",
		
		["Scope_macro"] = "COMPONENT_AT_SCOPE_MACRO",
		["Scope_macro_02"] = "COMPONENT_AT_SCOPE_MACRO_02",
		["Scope_small"] = "COMPONENT_AT_SCOPE_SMALL",
		["Scope_small_02"] = "COMPONENT_AT_SCOPE_SMALL_02",
		["Scope_medium"] = "COMPONENT_AT_SCOPE_MEDIUM",
		["Scope_large"] = "COMPONENT_AT_SCOPE_LARGE",
		["Scope_fixed"] = "COMPONENT_AT_SCOPE_LARGE_FIXED_ZOOM",
		
		["Scope_mk2"] = "COMPONENT_AT_SCOPE_MACRO_MK2",
		["Scope_mk2_02"] = "COMPONENT_AT_SCOPE_MACRO_MK2_02",
		["Scope_mk2_smg"] = "COMPONENT_AT_SCOPE_MACRO_MK2_smg",
		
		["Scope_mk2_small"] = "COMPONENT_AT_SCOPE_SMALL_MK2",
		["Scope_mk2_small_smg"] = "COMPONENT_AT_SCOPE_SMALL_SMG_MK2",
		
		["Large Scope"] = "COMPONENT_AT_SCOPE_MEDIUM_MK2",
		["Advanced Scope"] = "COMPONENT_AT_SCOPE_MAX",
		["Zoom_Scope_fixed"] = "COMPONENT_AT_SCOPE_LARGE_FIXED_ZOOM_MK2",
		["Zoom_Scope_mk2"] = "COMPONENT_AT_SCOPE_LARGE_MK2",
		["Night Vision Scope"] = "COMPONENT_AT_SCOPE_NV",
		["Thermal Scope"] = "COMPONENT_AT_SCOPE_THERMAL",
	
	},
	suppressor = {
		["pistol_supp"] = "COMPONENT_AT_PI_SUPP",
		["pistol_supp_02"] = "COMPONENT_AT_PI_SUPP_02",
		["AR_supp"] = "COMPONENT_AT_AR_SUPP",
		["AR_supp_02"] = "COMPONENT_AT_AR_SUPP_02",
		["special"] = "COMPONENT_CERAMICPISTOL_SUPP",
		["SR_supp"] = "COMPONENT_AT_SR_SUPP_03",
	},
	grip = {
		["AR_grip"] = "COMPONENT_AT_AR_AFGRIP",
		["AR_grip_02"] = "COMPONENT_AT_AR_AFGRIP_02",
	},
	Flashlight = {
		["pistol_flsh"] = "COMPONENT_AT_PI_FLSH",
		["pistol_flsh_02"] = "COMPONENT_AT_PI_FLSH_02",
		["AR_flsh"] = "COMPONENT_AT_AR_FLSH",
	},
	Rounds = {
		["Tracer Rounds"] = "CLIP_TRACER",
		["Incendiary Rounds"] = "CLIP_INCENDIARY",
		["Hollow Point Rounds"] = "CLIP_HOLLOWPOINT",
		["Full Metal Jacket Rounds"] = "CLIP_FMJ",
	},
}

return cfg